### ISSUE TITLE
Controlplane part of `forwarder-vpp` leaks

### ISSUE THREAD

**Issue by NikitaSkrynnik** [networkservicemesh/cmd-forwarder-vpp#1129]
## Description
`forwarder-vpp` has two interface leaks:
1. `timeout` chain element doesn't call `Close` for expired connections in `forwarder-vpp`. Therefore, `vpp` interfaces are not deleted
2. Even if we call `Close` in `forwarder-vpp` it doesn't delete `vxlan` interfaces

## Tasks
- [ ] Investigate why `timeout` doesn't call `Close` - 8h
   - [ ] Make `timeout` chain element close connetions faster - 1h 
   - [ ] Add  logs to `timeout` chain element - 1h
   - [ ] Run tests with the modified `timeout` - 3h
   - [ ] Check collected logs - 3h 
 - [ ] Fix `timeout` chain element - ?
 - [ ] Investigate why `forwarder-vpp` doesn't close `vxlan` interfaces - 6h
    - [ ] Run scaling tests - 3h
    - [ ] Check collected logs - 3h

**Comment by NikitaSkrynnik** [comment]
All changes that fix `tap` interface leaks are in these PRs:
1. https://github.com/networkservicemesh/sdk/pull/1643
2. https://github.com/networkservicemesh/sdk-vpp/pull/835

**Comment by denis-tingaikin** [comment]
Seems like the problem still exsisting and to forwarder is leaking:

![image](https://github.com/user-attachments/assets/e500880c-7a67-42fb-b00e-143761fcc3c2)

The picture shows mem consumption for forwarder vpp.


[forwarder-vpp_goroutineprofiles_20240920082027.tar.gz](https://github.com/user-attachments/files/17114429/forwarder-vpp_goroutineprofiles_20240920082027.tar.gz)
[forwarder-vpp_memprofiles_20240920082112.tar.gz](https://github.com/user-attachments/files/17114431/forwarder-vpp_memprofiles_20240920082112.tar.gz)

**Comment by NikitaSkrynnik** [comment]
### Current plan
- [ ] Test 40 clients and 1 endpoint on Azure cluster with 2 nodes for 24 hours. Collect memory, goroutine profiles, vpp memory profiles and `kubectl top` after 10 min of testing and after 24 hours of testing.
- [ ] Test 40 clients and 1 endpoint on Azure cluster with 2 nodes for 24 hours. Scale clients for 0 to 40 every 60 seconds. Collect memory, goroutine profiles, vpp memory profiles and `kubectl top` at the beginning, after 10 min of testing and after 24 hours of testing.

**Comment by NikitaSkrynnik** [comment]
After fixing context leaks in `nsmonitor` and `timeout` chain element forwarder shows the next results on 30 NSCs and 10 NSEs:

**3h of testing:**
```
nsm-system    forwarder-vpp-gr729                   135m         363Mi           
nsm-system    forwarder-vpp-zjd5x                   200m         390Mi           
nsm-system    nsmgr-25vvt                           167m         92Mi            
nsm-system    nsmgr-f6rjf                           92m          71Mi
```

**18h of testing:**
```
nsm-system    forwarder-vpp-gr729                   132m         401Mi           
nsm-system    forwarder-vpp-zjd5x                   199m         438Mi           
nsm-system    nsmgr-25vvt                           175m         97Mi            
nsm-system    nsmgr-f6rjf                           92m          74Mi 
```

**3d20h of testing:**
```
nsm-system    forwarder-vpp-gr729                   272m         421Mi           
nsm-system    forwarder-vpp-zjd5x                   310m         443Mi           
nsm-system    nsmgr-25vvt                           197m         103Mi           
nsm-system    nsmgr-f6rjf                           101m         78Mi   
```

**4d5h of testing:**
```
nsm-system    forwarder-vpp-gr729                   228m         417Mi           
nsm-system    forwarder-vpp-zjd5x                   203m         448Mi           
nsm-system    nsmgr-25vvt                           213m         101Mi           
nsm-system    nsmgr-f6rjf                           110m         83Mi  
```


**30m after testing:**
```
nsm-system    forwarder-vpp-gr729                   66m          414Mi           
nsm-system    forwarder-vpp-zjd5x                   63m          428Mi           
nsm-system    nsmgr-25vvt                           49m          87Mi            
nsm-system    nsmgr-f6rjf                           46m          73Mi 
```

memory and goroutine profiles don't show any leaks 30m after testing. Here are all profiles: [traces.zip](https://github.com/user-attachments/files/17366562/traces.zip)

**Comment by denis-tingaikin** [comment]
@NikitaSkrynnik attached archive is empty, could you resend it?

**Comment by NikitaSkrynnik** [comment]
We found that Go runtime in `nsmgr` (probably in `forwarder-vpp` too) is aware of the memory consumption shown by the metrics server in Kubernetes. Runtime can allocate big chunks of memory during highload tests but usually don't return them to the kernel. It's due to default memory management settings in Go.

This behaviour can be changed by setting env var `GODEBUG=madvdontneed=1`. It makes Go runtime return memory to the kernel as soon as the memory is not needed.

**Comment by NikitaSkrynnik** [comment]
### Forwarder VPPTesting

After 150h of highload testing with 30 clients and 10 endpoints on Azure cluster `forwarder` memory growth is:
![chart](https://github.com/user-attachments/assets/f252e26e-787c-4c44-ba9f-a30d866bfcc7)

`forwarder` memory consumption is slowly growing. Go memory profiles show `6mb` of allocated memory after 150h, goroutine count is `288`. 

`vpp` memory usage for `forwarder-vpp-qhn7q` is:
![chart (1)](https://github.com/user-attachments/assets/838e235b-3faa-405d-87f3-dfb8c99cf928)

**Comment by NikitaSkrynnik** [comment]
Hi, @szvincze! We don't see any memory leaks on our side. Could you tell about your test results? Is everything stable on your side? Can we close this issue?

**Comment by denis-tingaikin** [comment]
@szvincze we've added a potential fix for the problem https://github.com/networkservicemesh/sdk-vpp/pull/877
if you get a chance please test latest main images.
